### ISSUE TITLE
timezoneデータについて確認です。

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/DataTypes#11]
data_type_choicesテーブルから、データが消えて、PHPのDateTimeZoneクラスを使用するようになっています。

こっちで良い気はするのですが、データで保持してた時のメリットとしては、他の選択肢データと扱いが共通になるくらいだったでしょうか？
何か他にもあって、ちょっと悩んだ記憶があるのですが、もし覚えていたらメモとして、ここにあげといた方が良いと思いました。特になければCloseします。

**Comment by s-nakajima** [comment]
問題ってほどではないですが、私の記憶では言語化どうしようかという話と、DateTimeZoneクラスの全部出すと見づらいってことは、覚えてますが・・・他はちょっと記憶ないです。

ちなみに言語化は、Google翻訳です。

**Comment by kteraguchi** [comment]
あー、言語化です。了解しました。現状処理で対応しているのでOKですね。Closeします。
