### ISSUE TITLE
DataTypeFormHelperのHash::combine

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/DataTypes#13]
https://github.com/NetCommons3/DataTypes/blob/d0945e67709b1f755095d66e81f0f1e05cd3be69/View/Helper/DataTypeFormHelper.php#L54

モデルからデータを取得する際に、Hash::combineしているっぽいので、DataTypeFormHelperでは不要だと思います。

**Comment by s-nakajima** [comment]
これ、FormHelper::selectのオプションにセットするようにcombineしています。
なので、必要なcombineです。
